name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Ou "master", dependendo do nome da sua branch principal

# Permissões necessárias para publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Fazer upload dos arquivos estáticos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Aqui ele pega todos os arquivos (index, webapp, apresentacao, modelo_tfjs)
          
      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
